language: python
python:
    - 3.6
install:
    - pip3 install -r requirements.txt
script:
    - python3 manage.py test

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: darshil
  run: 
    - git checkout .pyc
    - python3 manage.py migrate
  on: master
